export const GET_MY_SUBMISSIONS_SUCCESS = 'GET_MY_SUBMISSIONS_SUCCESS';
export const GET_MY_SUBMISSIONS_FAIL = 'GET_MY_SUBMISSIONS_FAIL';

export const GET_ALL_SUBMISSIONS_SUCCESS = 'GET_ALL_SUBMISSIONS_SUCCESS';
export const GET_ALL_SUBMISSIONS_FAIL = 'GET_ALL_SUBMISSIONS_FAIL';

export const CREATE_EMPTY_SUBMISSION_SUCCESS = 'CREATE_EMPTY_SUBMISSION';
export const CREATE_EMPTY_SUBMISSION_FAIL = 'CREATE_EMPTY_SUBMISSION_FAIL';

