export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';
export const LOGOUT = 'LOGOUT';
export const PROFILE_LOADED_SUCCESS = 'PROFILE_LOADED_SUCCESS';
export const PROFILE_LOADED_FAIL = 'PROFILE_LOADED_FAIL';
export const EDIT_GS_PROFILE_SUCCESS = 'EDIT_GS_PROFILE_SUCCESS';
export const EDIT_GS_PROFILE_FAIL = 'EDIT_GS_PROFILE_FAIL';
export const EDIT_MH_PROFILE_SUCCESS = 'EDIT_MH_PROFILE_SUCCESS';
export const EDIT_MH_PROFILE_FAIL = 'EDIT_MH_PROFILE_FAIL';
export const EDIT_TEETH_PREFS_FAIL = 'EDIT_TEETH_PREFS_FAIL';
export const EDIT_TEETH_PREFS_SUCCESS = 'EDIT_TEETH_PREFS_SUCCESS';


 